//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Octopus.rc
//
#define TIMER_TEMP                      10
#define TIMER_LAMBDA                    11
#define TIMER_SCRIPT                    12
#define TIMER_SCAN                      13
#define TIMER_STAGE                     14
#define TIMER_PIEZO                     15
#define TIMER_ADC                       16
#define TIMER_POSITION                  17
#define TIMER_MPC                       18
#define TIMER_MPC_FB                    19
#define TIMER_MPC_SPREAD                20
#define TIMER_MOTOR                     21
#define IDC_BACKGROUND                  101
#define IDB_RUNNING                     115
#define IDB_STOPPED                     116
#define IDR_MAINFRAME                   127
#define IDR_OctopusTYPE                 128
#define IDS_OBJECT_PROPERTIES           131
#define IDS_APP_TITLE                   132
#define IDD_ABOUTBOX                    133
#define IDB_NO                          144
#define IDB_YES                         145
#define IDC_STATUS_OPEN_ANDOR           951
#define IDC_STATUS_OPEN_WHEEL           953
#define IDC_STATUS_OPEN_AOTF            954
#define IDC_STATUS_OPEN_SCRIPT          955
#define IDC_STATUS_OPEN_MOTOR           956
#define IDC_STATUS_OPEN_LED             957
#define IDC_STATUS_OPEN_STAGE           958
#define IDC_STATUS_OPEN_MPC200          959
#define IDC_STATUS_OPEN_SCOPE           960
#define IDC_STAGE_545                   1046
#define IDC_STAGE_686                   1047
#define IDC_STAGE_CORRECT_XY            1048
#define IDC_STAGE_CENTER                1049
#define IDC_STAGE_POS                   1050
#define IDC_STAGE_DOWN                  1051
#define IDC_STAGE_UP                    1052
#define IDC_STAGE_FWD                   1053
#define IDC_STAGE_BACK                  1054
#define IDC_STAGE_RIGHT                 1055
#define IDC_STAGE_LEFT                  1056
#define IDC_STAGE_SSIZE_1               1058
#define IDC_STAGE_SSIZE_2               1059
#define IDC_STAGE_SSIZE_3               1060
#define IDC_STAGE_SSIZE_4               1061
#define IDC_STAGE_SSIZE_5               1062
#define IDC_STAGE_SCAN                  1065
#define IDC_STAGE_SCAN_Y                1066
#define IDC_STAGE_SCAN_X                1067
#define IDC_STAGE_SCAN_STEP_SIZE        1068
#define IDC_STAGE_STEP                  1069
#define IDC_STAGE_SAVE                  1070
#define IDC_STAGE_SAVE_GOTO             1071
#define IDC_STAGE_POS_SAVE              1072
#define IDC_LASERS                      1073
#define IDC_LASER_405                   1074
#define IDC_LASER_405ONOFF_BMP          1075
#define IDC_LASER_488                   1076
#define IDC_LASER_488ONOFF_BMP          1077
#define IDC_LASER_561                   1078
#define IDC_LASER_561ONOFF_BMP          1079
#define IDC_LASER_639                   1080
#define IDC_LASER_639ONOFF_BMP          1081
#define IDC_MGSHUTTERCTRL1              1082
#define IDC_MGSHUTTERCTRL2              1083
#define IDC_MGSHUTTERCTRL3              1084
#define IDC_MGSHUTTERCTRL4              1085
#define IDC_MG17LOGGERCTRL1             1086
#define IDC_MG17SYSTEMCTRL1             1087
#define IDC_CAMERA                      1600
#define IDC_CAS_DISP                    1601
#define IDC_TIME                        1602
#define IDC_CAS_STARTSTOP_PICTURE       1603
#define IDC_CAS_STARTSTOP_MOVIE         1604
#define IDC_CAS_MANUAL_GAIN             1605
#define IDC_CAS_DISPLAY_GAIN_MANUAL     1642
#define IDC_CAS_DISPLAY_GAIN_AUTOMATIC  1643
#define IDC_CAS_PICTURES_PER_FILE       1644
#define IDC_CAS_TEMP_TARGET             1646
#define IDC_CAS_TEMP_CURRENT            1647
#define IDC_CAS_DISPLAY_BIN_1           1648
#define IDC_CAS_DISPLAY_BIN_2           1649
#define IDC_CAS_DISPLAY_BIN_4           1650
#define IDC_CAS_DISPLAY_BIN_8           1651
#define IDC_CAS_GAIN_SINGLE             1652
#define IDC_CAS_EXPOSURE_TIME_SINGLE    1653
#define IDC_CAS_GAIN_MOVIE              1654
#define IDC_CAS_EXPOSURE_TIME_MOVIE     1655
#define IDC_CAS_START_MOVIE             1658
#define IDC_CAS_STOP_MOVIE              1660
#define IDC_CAS_PATHNAME                1662
#define IDC_CAS_SETPATH                 1663
#define IDC_CAS_PATH                    1664
#define IDC_CAS_SAVEONOFF_BMP           1665
#define IDC_CAS_SAVEONOFF               1666
#define IDC_CAS_FILEPREFIX              1667
#define IDC_CAS_PICTURES_SKIP           1668
#define IDC_CAS_PICTURES_SKIP_IND       1669
#define IDC_CAS_VSSPEED_1               1700
#define IDC_CAS_VSSPEED_2               1701
#define IDC_CAS_VSSPEED_3               1702
#define IDC_CAS_VSSPEED_4               1703
#define IDC_CAS_VSSPEED_0               1704
#define IDC_CAS_HSSPEED_1               1705
#define IDC_CAS_HSSPEED_2               1706
#define IDC_CAS_HSSPEED_3               1707
#define IDC_CAS_HSSPEED_4               1708
#define IDC_CAS_HSSPEED_5               1709
#define IDC_CAS_HSSPEED_0               1710
#define IDC_CAS_FT                      1711
#define IDC_CAS_TTL                     1712
#define IDC_CAS_GL_0                    1713
#define IDC_CAS_GL_1                    1714
#define IDC_CAS_GL_2                    1715
#define IDC_CAM_SCOPE                   1716
#define IDC_CAS_FOCUSONOFF_BMP          1800
#define IDC_CAS_FOCUSONOFF              1801
#define IDC_STATIC_GAIN1                1802
#define IDC_STATIC_GAIN2                1803
#define IDC_LAMBDA                      3042
#define IDC_SHUTTER_SLIDER              3043
#define IDC_SHUTTER_SLIDER_SETTING      3044
#define IDC_RADIO_SHUTR_OPEN            3045
#define IDC_RADIO_SHUTR_CLOSE           3046
#define IDC_RADIO_SHUTR_PARTIAL         3047
#define IDC_RADIO_FILTER_0              3055
#define IDC_RADIO_FILTER_1              3056
#define IDC_RADIO_FILTER_2              3057
#define IDC_RADIO_FILTER_3              3058
#define IDC_RADIO_FILTER_4              3059
#define IDC_RADIO_FILTER_5              3060
#define IDC_RADIO_FILTER_6              3061
#define IDC_RADIO_FILTER_7              3062
#define IDC_RADIO_FILTER_8              3063
#define IDC_RADIO_FILTER_9              3064
#define IDC_SCRIPT                      3100
#define IDC_LIST_SEQUENCE               3101
#define IDC_BUTTON_SEQ_LOAD             3102
#define IDC_BUTTON_SEQ_RUN              3103
#define IDC_BUTTON_SEQ_STOP             3104
#define IDC_SCR_RUNNING_BMP             3105
#define IDC_SCR_CYCLE                   3106
#define IDC_LED                         3200
#define IDC_LED_INTENSITY_SLIDER        3201
#define IDC_LED_INTENSITY               3202
#define IDC_LED_ADC                     3203
#define IDC_AOTF                        4001
#define IDC_AOTF_FREQ                   4002
#define IDC_AOTF_CH_1                   4003
#define IDC_AOTF_CH_2                   4004
#define IDC_AOTF_STARTSTOP              4005
#define IDC_AOTF_ONOFF_BMP              4006
#define IDC_SCOPE                       5001
#define IDC_SCOPE_SSIZE_1               5003
#define IDC_SCOPE_SSIZE_2               5004
#define IDC_SCOPE_SSIZE_3               5005
#define IDC_SCOPE_SSIZE_4               5006
#define IDC_SCOPE_POS                   5007
#define IDC_SCOPE_DOWN                  5008
#define IDC_SCOPE_UP                    5009
#define IDC_SCOPE_ESC                   5010
#define IDC_SCOPE_RTN                   5011
#define IDC_SCOPE_OB_1                  5012
#define IDC_SCOPE_OB_2                  5013
#define IDC_SCOPE_OB_3                  5014
#define IDC_SCOPE_OB_4                  5015
#define IDC_SCOPE_OB_5                  5016
#define IDC_SCOPE_OB_6                  5017
#define IDC_SCOPE_CLEAN_TO              5019
#define IDC_SCOPE_CLEAN_FROM            5020
#define IDC_SCOPE_INTENSITY_SLIDER      5021
#define IDC_SCOPE_INTENSITY_SLIDER_SETTING 5022
#define IDC_SCOPE_MU_1                  5023
#define IDC_SCOPE_MU_2                  5024
#define IDC_SCOPE_MU_3                  5025
#define IDC_SCOPE_MU_4                  5026
#define IDC_SCOPE_MU_5                  5027
#define IDC_SCOPE_MU_6                  5028
#define IDC_SCOPE_BF_1                  5029
#define IDC_SCOPE_BF_2                  5030
#define IDC_SCOPE_BF_3                  5031
#define IDC_SCOPE_BF_4                  5032
#define IDC_SCOPE_BF_5                  5033
#define IDC_SCOPE_BF_6                  5034
#define IDC_SCOPE_CO_1                  6029
#define IDC_SCOPE_CO_2                  6030
#define IDC_SCOPE_CO_3                  6031
#define IDC_SCOPE_CO_4                  6032
#define IDC_SCOPE_CO_5                  6033
#define IDC_SCOPE_CO_6                  6034
#define IDC_SCOPE_LIST_SEQUENCE         6035
#define IDC_SCOPE_PATH_EYE              6036
#define IDC_SCOPE_PATH_CAMERA           6037
#define IDC_STATUS_OPEN_PIEZO           6108
#define IDC_PIEZO                       6109
#define IDC_PIEZO_DOWN                  6110
#define IDC_PIEZO_CENTER                6111
#define IDC_PIEZO_UP                    6112
#define IDC_PIEZO_SAVE                  6113
#define IDC_PIEZO_SAVE_GOTO             6114
#define IDC_PIEZO_SSIZE_1               6115
#define IDC_PIEZO_SSIZE_2               6116
#define IDC_PIEZO_SSIZE_3               6117
#define IDC_PIEZO_SSIZE_4               6118
#define IDC_PIEZO_POS                   6119
#define IDC_PIEZO_FOCUS                 6120
#define IDC_PIEZO_FOCUS_SCORE           6121
#define IDC_PIEZO_FOCUS_RUNNING_BMP     6122
#define IDC_PIEZO_CENTERXY              6123
#define IDC_MPC200                      7049
#define IDC_MPC_GO_XYZ                  7050
#define IDC_MPC_RE_dX                   7051
#define IDC_MPC_RE_dY                   7052
#define IDC_MPC_RE_dZ                   7053
#define IDC_MPC_RE_SPEED                7054
#define IDC_MPC_GO_CENTER               7055
#define IDC_MPC_CENTER                  7056
#define IDC_POS_X                       7057
#define IDC_POS_Y                       7058
#define IDC_POS_Z                       7059
#define IDC_MPC_STOP                    7060
#define IDC_MPC200_LIST_SEQUENCE        7071
#define IDC_POS_FORCE                   7083
#define IDC_MPC_FF_VOLTAGE              7084
#define IDC_MPC_FF_FORCE                7085
#define IDC_MPC_FF_ZERO                 7086
#define IDC_MPC_FF_FORCE_AVG            7087
#define IDC_MPC_CFFL_K                  7088
#define IDC_MPC_CFFL_TARGET_FORCE       7089
#define IDC_MPC_CFFL_MARGIN             7090
#define IDC_MPC_CFFL_SPEED              7091
#define IDC_MPC_CFFL_STOP               7092
#define IDC_MPC_CFFL_START              7093
#define IDC_MPC_CFFL_RUNTIME            7094
#define IDC_MPC_CFFL_ONOFF_BMP          7095
#define IDC_MPC_CFFL_PROBE_SENS         7096
#define IDC_MPC_CFFL_MOV_LIMIT          7097
#define IDC_MPC_SPREAD_SS               7101
#define IDC_MPC_SPREAD_DELAY            7102
#define IDC_MPC_SPREAD_STOP             7103
#define IDC_MPC_SPREAD_START            7104
#define IDC_MPC_SPREAD_ONOFF_BMP        7105
#define IDC_MPC_SPREAD_CYCLES           7106
#define IDC_MPC_FB_STEP_FAST            8001
#define IDC_MPC_FB_CYCLES_FAST          8002
#define IDC_MPC_FB_SPEED_FAST           8003
#define IDC_MPC_FB_WAIT_FAST            8004
#define IDC_MPC_FB_GO_FAST              8005
#define IDC_MPC_FB_GO_SLOW              8006
#define IDC_MPC_FB_WAIT_SLOW            8007
#define IDC_MPC_FB_SPEED_SLOW           8008
#define IDC_MPC_FB_CYCLES_SLOW          8009
#define IDC_MPC_FB_STEP_SLOW            8010
#define IDC_MPC_X                       8011
#define IDC_MPC_Z                       8012
#define IDC_MOTOR                       8012
#define IDC_MPC200_PLOT                 8013
#define IDC_MOTOR_SAVE_GOTO             8013
#define IDC_MOTOR_SAVE                  8014
#define IDC_MOTOR_POS                   8015
#define IDC_MOTOR_DOWN                  8016
#define IDC_MOTOR_UP                    8017
#define IDC_MOTOR_CENTER                8018
#define IDC_MOTOR_SSIZE_1               8019
#define IDC_MOTOR_SSIZE_2               8020
#define IDC_MGMOTORCTRL1                8021

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40016
#define _APS_NEXT_CONTROL_VALUE         8002
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
